spring:
  application:
    name: engine

task:
  rate: 5000

parser:
  url: http://185.223.93.175:8091/

bot:
  url:

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true